/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface AdminInterface extends ethers.utils.Interface {
  functions: {
    'addAggregator(address,address,address)': FunctionFragment;
    'addSavingsAccountStrategy(address,address)': FunctionFragment;
    'addTokenAddressForCompoundYield(address,address,address)': FunctionFragment;
    'addVerifier(address,address)': FunctionFragment;
    'changeImplementationAddressOfProxy(address,address)': FunctionFragment;
    'deployCompoundYield(address,address,address,address)': FunctionFragment;
    'deployMockAdminVerifier(address,address)': FunctionFragment;
    'deployMockCToken(address,address)': FunctionFragment;
    'deployNoYield(address,address,address)': FunctionFragment;
    'deployPriceOracle(address,address,uint32)': FunctionFragment;
    'deploySavingsAccount(address,address)': FunctionFragment;
    'deployStrategyRegistry(address,uint256)': FunctionFragment;
    'deployVerification(address)': FunctionFragment;
    'emergencyWithdrawFromCompoundYield(address,address,address)': FunctionFragment;
    'emergencyWithdrawFromNoYield(address,address,uint256)': FunctionFragment;
    'execute(address,uint256,bytes)': FunctionFragment;
    'executeFuncSig(address,uint256,string,bytes)': FunctionFragment;
    'forceUpdateTokenAddressForCompoundYield(address,address,address)': FunctionFragment;
    'getFunctionSignature(string)': FunctionFragment;
    'getImplementationAddressOfProxy(address)': FunctionFragment;
    'initSavingsAccount(address,address)': FunctionFragment;
    'setChainlinkFeedAddress(address,address,address)': FunctionFragment;
    'setDepositLimitForCompoundYield(address,address,uint256)': FunctionFragment;
    'setUpAllOracles(address)': FunctionFragment;
    'setUpChainlinkOracles(address)': FunctionFragment;
    'setUpUniswapOracles(address)': FunctionFragment;
    'setUp_USDC_ETH_oracles(address)': FunctionFragment;
    'transferOwnership(address,address)': FunctionFragment;
    'transferToken(address,address,uint256)': FunctionFragment;
    'updateProtocolFeeFraction(address,uint256)': FunctionFragment;
    'verifyUser(address,address)': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'addAggregator', values: [string, string, string]): string;
  encodeFunctionData(functionFragment: 'addSavingsAccountStrategy', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'addTokenAddressForCompoundYield', values: [string, string, string]): string;
  encodeFunctionData(functionFragment: 'addVerifier', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'changeImplementationAddressOfProxy', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'deployCompoundYield', values: [string, string, string, string]): string;
  encodeFunctionData(functionFragment: 'deployMockAdminVerifier', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'deployMockCToken', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'deployNoYield', values: [string, string, string]): string;
  encodeFunctionData(functionFragment: 'deployPriceOracle', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'deploySavingsAccount', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'deployStrategyRegistry', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'deployVerification', values: [string]): string;
  encodeFunctionData(functionFragment: 'emergencyWithdrawFromCompoundYield', values: [string, string, string]): string;
  encodeFunctionData(functionFragment: 'emergencyWithdrawFromNoYield', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'execute', values: [string, BigNumberish, BytesLike]): string;
  encodeFunctionData(functionFragment: 'executeFuncSig', values: [string, BigNumberish, string, BytesLike]): string;
  encodeFunctionData(functionFragment: 'forceUpdateTokenAddressForCompoundYield', values: [string, string, string]): string;
  encodeFunctionData(functionFragment: 'getFunctionSignature', values: [string]): string;
  encodeFunctionData(functionFragment: 'getImplementationAddressOfProxy', values: [string]): string;
  encodeFunctionData(functionFragment: 'initSavingsAccount', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'setChainlinkFeedAddress', values: [string, string, string]): string;
  encodeFunctionData(functionFragment: 'setDepositLimitForCompoundYield', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'setUpAllOracles', values: [string]): string;
  encodeFunctionData(functionFragment: 'setUpChainlinkOracles', values: [string]): string;
  encodeFunctionData(functionFragment: 'setUpUniswapOracles', values: [string]): string;
  encodeFunctionData(functionFragment: 'setUp_USDC_ETH_oracles', values: [string]): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'transferToken', values: [string, string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'updateProtocolFeeFraction', values: [string, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'verifyUser', values: [string, string]): string;

  decodeFunctionResult(functionFragment: 'addAggregator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'addSavingsAccountStrategy', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'addTokenAddressForCompoundYield', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'addVerifier', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'changeImplementationAddressOfProxy', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deployCompoundYield', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deployMockAdminVerifier', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deployMockCToken', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deployNoYield', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deployPriceOracle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deploySavingsAccount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deployStrategyRegistry', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'deployVerification', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'emergencyWithdrawFromCompoundYield', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'emergencyWithdrawFromNoYield', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'executeFuncSig', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'forceUpdateTokenAddressForCompoundYield', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getFunctionSignature', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getImplementationAddressOfProxy', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'initSavingsAccount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setChainlinkFeedAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setDepositLimitForCompoundYield', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setUpAllOracles', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setUpChainlinkOracles', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setUpUniswapOracles', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setUp_USDC_ETH_oracles', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferToken', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'updateProtocolFeeFraction', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'verifyUser', data: BytesLike): Result;

  events: {};
}

export class Admin extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AdminInterface;

  functions: {
    addAggregator(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'addAggregator(address,address,address)'(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addSavingsAccountStrategy(
      _strategyRegistry: string,
      _strategyAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'addSavingsAccountStrategy(address,address)'(
      _strategyRegistry: string,
      _strategyAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addTokenAddressForCompoundYield(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'addTokenAddressForCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addVerifier(
      _verification: string,
      _verifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'addVerifier(address,address)'(
      _verification: string,
      _verifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeImplementationAddressOfProxy(
      proxy: string,
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'changeImplementationAddressOfProxy(address,address)'(
      proxy: string,
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployCompoundYield(
      _admin: string,
      _savingsAccount: string,
      _mockWETH: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'deployCompoundYield(address,address,address,address)'(
      _admin: string,
      _savingsAccount: string,
      _mockWETH: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployMockAdminVerifier(
      arg0: string,
      _verification: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'deployMockAdminVerifier(address,address)'(
      arg0: string,
      _verification: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployMockCToken(
      _mockToken: string,
      _compoundYield: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'deployMockCToken(address,address)'(
      _mockToken: string,
      _compoundYield: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployNoYield(
      _admin: string,
      _savingsAccount: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'deployNoYield(address,address,address)'(
      _admin: string,
      _savingsAccount: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployPriceOracle(
      _admin: string,
      _weth: string,
      _uniswapPriceAvgPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'deployPriceOracle(address,address,uint32)'(
      _admin: string,
      _weth: string,
      _uniswapPriceAvgPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deploySavingsAccount(
      arg0: string,
      _strategyRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'deploySavingsAccount(address,address)'(
      arg0: string,
      _strategyRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployStrategyRegistry(
      arg0: string,
      _maxStrategies: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'deployStrategyRegistry(address,uint256)'(
      arg0: string,
      _maxStrategies: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployVerification(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'deployVerification(address)'(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    emergencyWithdrawFromCompoundYield(
      yield: string,
      _asset: string,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'emergencyWithdrawFromCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    emergencyWithdrawFromNoYield(
      yield: string,
      _asset: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'emergencyWithdrawFromNoYield(address,address,uint256)'(
      yield: string,
      _asset: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    execute(
      target: string,
      value: BigNumberish,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'execute(address,uint256,bytes)'(
      target: string,
      value: BigNumberish,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeFuncSig(
      target: string,
      value: BigNumberish,
      signature: string,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'executeFuncSig(address,uint256,string,bytes)'(
      target: string,
      value: BigNumberish,
      signature: string,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    forceUpdateTokenAddressForCompoundYield(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'forceUpdateTokenAddressForCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getFunctionSignature(signature: string, overrides?: CallOverrides): Promise<[string]>;

    'getFunctionSignature(string)'(signature: string, overrides?: CallOverrides): Promise<[string]>;

    getImplementationAddressOfProxy(
      sublimeProxyInstance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'getImplementationAddressOfProxy(address)'(
      sublimeProxyInstance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initSavingsAccount(
      savingsAccount: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'initSavingsAccount(address,address)'(
      savingsAccount: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setChainlinkFeedAddress(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'setChainlinkFeedAddress(address,address,address)'(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDepositLimitForCompoundYield(
      _compound: string,
      _asset: string,
      _limit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'setDepositLimitForCompoundYield(address,address,uint256)'(
      _compound: string,
      _asset: string,
      _limit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUpAllOracles(priceOracleAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'setUpAllOracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUpChainlinkOracles(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'setUpChainlinkOracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUpUniswapOracles(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'setUpUniswapOracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUp_USDC_ETH_oracles(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'setUp_USDC_ETH_oracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      _contract: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'transferOwnership(address,address)'(
      _contract: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferToken(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'transferToken(address,address,uint256)'(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateProtocolFeeFraction(
      creditLine: string,
      protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'updateProtocolFeeFraction(address,uint256)'(
      creditLine: string,
      protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    verifyUser(_user: string, _verifier: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'verifyUser(address,address)'(
      _user: string,
      _verifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addAggregator(
    priceOracle: string,
    token: string,
    aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'addAggregator(address,address,address)'(
    priceOracle: string,
    token: string,
    aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addSavingsAccountStrategy(
    _strategyRegistry: string,
    _strategyAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'addSavingsAccountStrategy(address,address)'(
    _strategyRegistry: string,
    _strategyAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addTokenAddressForCompoundYield(
    yield: string,
    _asset: string,
    _liquidityToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'addTokenAddressForCompoundYield(address,address,address)'(
    yield: string,
    _asset: string,
    _liquidityToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addVerifier(
    _verification: string,
    _verifier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'addVerifier(address,address)'(
    _verification: string,
    _verifier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeImplementationAddressOfProxy(
    proxy: string,
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'changeImplementationAddressOfProxy(address,address)'(
    proxy: string,
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployCompoundYield(
    _admin: string,
    _savingsAccount: string,
    _mockWETH: string,
    _treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'deployCompoundYield(address,address,address,address)'(
    _admin: string,
    _savingsAccount: string,
    _mockWETH: string,
    _treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployMockAdminVerifier(
    arg0: string,
    _verification: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'deployMockAdminVerifier(address,address)'(
    arg0: string,
    _verification: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployMockCToken(
    _mockToken: string,
    _compoundYield: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'deployMockCToken(address,address)'(
    _mockToken: string,
    _compoundYield: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployNoYield(
    _admin: string,
    _savingsAccount: string,
    _treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'deployNoYield(address,address,address)'(
    _admin: string,
    _savingsAccount: string,
    _treasury: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployPriceOracle(
    _admin: string,
    _weth: string,
    _uniswapPriceAvgPeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'deployPriceOracle(address,address,uint32)'(
    _admin: string,
    _weth: string,
    _uniswapPriceAvgPeriod: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deploySavingsAccount(
    arg0: string,
    _strategyRegistry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'deploySavingsAccount(address,address)'(
    arg0: string,
    _strategyRegistry: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployStrategyRegistry(
    arg0: string,
    _maxStrategies: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'deployStrategyRegistry(address,uint256)'(
    arg0: string,
    _maxStrategies: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployVerification(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'deployVerification(address)'(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  emergencyWithdrawFromCompoundYield(
    yield: string,
    _asset: string,
    _wallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'emergencyWithdrawFromCompoundYield(address,address,address)'(
    yield: string,
    _asset: string,
    _wallet: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  emergencyWithdrawFromNoYield(
    yield: string,
    _asset: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'emergencyWithdrawFromNoYield(address,address,uint256)'(
    yield: string,
    _asset: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  execute(
    target: string,
    value: BigNumberish,
    callData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'execute(address,uint256,bytes)'(
    target: string,
    value: BigNumberish,
    callData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeFuncSig(
    target: string,
    value: BigNumberish,
    signature: string,
    callData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'executeFuncSig(address,uint256,string,bytes)'(
    target: string,
    value: BigNumberish,
    signature: string,
    callData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  forceUpdateTokenAddressForCompoundYield(
    yield: string,
    _asset: string,
    _liquidityToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'forceUpdateTokenAddressForCompoundYield(address,address,address)'(
    yield: string,
    _asset: string,
    _liquidityToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getFunctionSignature(signature: string, overrides?: CallOverrides): Promise<string>;

  'getFunctionSignature(string)'(signature: string, overrides?: CallOverrides): Promise<string>;

  getImplementationAddressOfProxy(
    sublimeProxyInstance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'getImplementationAddressOfProxy(address)'(
    sublimeProxyInstance: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initSavingsAccount(
    savingsAccount: string,
    _owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'initSavingsAccount(address,address)'(
    savingsAccount: string,
    _owner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setChainlinkFeedAddress(
    priceOracle: string,
    token: string,
    aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'setChainlinkFeedAddress(address,address,address)'(
    priceOracle: string,
    token: string,
    aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDepositLimitForCompoundYield(
    _compound: string,
    _asset: string,
    _limit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'setDepositLimitForCompoundYield(address,address,uint256)'(
    _compound: string,
    _asset: string,
    _limit: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUpAllOracles(priceOracleAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'setUpAllOracles(address)'(
    priceOracleAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUpChainlinkOracles(
    priceOracleAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'setUpChainlinkOracles(address)'(
    priceOracleAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUpUniswapOracles(
    priceOracleAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'setUpUniswapOracles(address)'(
    priceOracleAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUp_USDC_ETH_oracles(
    priceOracleAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'setUp_USDC_ETH_oracles(address)'(
    priceOracleAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    _contract: string,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'transferOwnership(address,address)'(
    _contract: string,
    _to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferToken(
    token: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'transferToken(address,address,uint256)'(
    token: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateProtocolFeeFraction(
    creditLine: string,
    protocolFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'updateProtocolFeeFraction(address,uint256)'(
    creditLine: string,
    protocolFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  verifyUser(_user: string, _verifier: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'verifyUser(address,address)'(
    _user: string,
    _verifier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addAggregator(priceOracle: string, token: string, aggregator: string, overrides?: CallOverrides): Promise<void>;

    'addAggregator(address,address,address)'(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addSavingsAccountStrategy(_strategyRegistry: string, _strategyAddress: string, overrides?: CallOverrides): Promise<void>;

    'addSavingsAccountStrategy(address,address)'(
      _strategyRegistry: string,
      _strategyAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addTokenAddressForCompoundYield(yield: string, _asset: string, _liquidityToken: string, overrides?: CallOverrides): Promise<void>;

    'addTokenAddressForCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addVerifier(_verification: string, _verifier: string, overrides?: CallOverrides): Promise<void>;

    'addVerifier(address,address)'(_verification: string, _verifier: string, overrides?: CallOverrides): Promise<void>;

    changeImplementationAddressOfProxy(proxy: string, newImplementation: string, overrides?: CallOverrides): Promise<void>;

    'changeImplementationAddressOfProxy(address,address)'(
      proxy: string,
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    deployCompoundYield(
      _admin: string,
      _savingsAccount: string,
      _mockWETH: string,
      _treasury: string,
      overrides?: CallOverrides
    ): Promise<string>;

    'deployCompoundYield(address,address,address,address)'(
      _admin: string,
      _savingsAccount: string,
      _mockWETH: string,
      _treasury: string,
      overrides?: CallOverrides
    ): Promise<string>;

    deployMockAdminVerifier(arg0: string, _verification: string, overrides?: CallOverrides): Promise<string>;

    'deployMockAdminVerifier(address,address)'(arg0: string, _verification: string, overrides?: CallOverrides): Promise<string>;

    deployMockCToken(_mockToken: string, _compoundYield: string, overrides?: CallOverrides): Promise<string>;

    'deployMockCToken(address,address)'(_mockToken: string, _compoundYield: string, overrides?: CallOverrides): Promise<string>;

    deployNoYield(_admin: string, _savingsAccount: string, _treasury: string, overrides?: CallOverrides): Promise<string>;

    'deployNoYield(address,address,address)'(
      _admin: string,
      _savingsAccount: string,
      _treasury: string,
      overrides?: CallOverrides
    ): Promise<string>;

    deployPriceOracle(_admin: string, _weth: string, _uniswapPriceAvgPeriod: BigNumberish, overrides?: CallOverrides): Promise<string>;

    'deployPriceOracle(address,address,uint32)'(
      _admin: string,
      _weth: string,
      _uniswapPriceAvgPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    deploySavingsAccount(arg0: string, _strategyRegistry: string, overrides?: CallOverrides): Promise<string>;

    'deploySavingsAccount(address,address)'(arg0: string, _strategyRegistry: string, overrides?: CallOverrides): Promise<string>;

    deployStrategyRegistry(arg0: string, _maxStrategies: BigNumberish, overrides?: CallOverrides): Promise<string>;

    'deployStrategyRegistry(address,uint256)'(arg0: string, _maxStrategies: BigNumberish, overrides?: CallOverrides): Promise<string>;

    deployVerification(arg0: string, overrides?: CallOverrides): Promise<string>;

    'deployVerification(address)'(arg0: string, overrides?: CallOverrides): Promise<string>;

    emergencyWithdrawFromCompoundYield(yield: string, _asset: string, _wallet: string, overrides?: CallOverrides): Promise<void>;

    'emergencyWithdrawFromCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _wallet: string,
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyWithdrawFromNoYield(yield: string, _asset: string, _amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'emergencyWithdrawFromNoYield(address,address,uint256)'(
      yield: string,
      _asset: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    execute(target: string, value: BigNumberish, callData: BytesLike, overrides?: CallOverrides): Promise<void>;

    'execute(address,uint256,bytes)'(target: string, value: BigNumberish, callData: BytesLike, overrides?: CallOverrides): Promise<void>;

    executeFuncSig(target: string, value: BigNumberish, signature: string, callData: BytesLike, overrides?: CallOverrides): Promise<void>;

    'executeFuncSig(address,uint256,string,bytes)'(
      target: string,
      value: BigNumberish,
      signature: string,
      callData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    forceUpdateTokenAddressForCompoundYield(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    'forceUpdateTokenAddressForCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    getFunctionSignature(signature: string, overrides?: CallOverrides): Promise<string>;

    'getFunctionSignature(string)'(signature: string, overrides?: CallOverrides): Promise<string>;

    getImplementationAddressOfProxy(sublimeProxyInstance: string, overrides?: CallOverrides): Promise<string>;

    'getImplementationAddressOfProxy(address)'(sublimeProxyInstance: string, overrides?: CallOverrides): Promise<string>;

    initSavingsAccount(savingsAccount: string, _owner: string, overrides?: CallOverrides): Promise<void>;

    'initSavingsAccount(address,address)'(savingsAccount: string, _owner: string, overrides?: CallOverrides): Promise<void>;

    setChainlinkFeedAddress(priceOracle: string, token: string, aggregator: string, overrides?: CallOverrides): Promise<void>;

    'setChainlinkFeedAddress(address,address,address)'(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setDepositLimitForCompoundYield(_compound: string, _asset: string, _limit: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'setDepositLimitForCompoundYield(address,address,uint256)'(
      _compound: string,
      _asset: string,
      _limit: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setUpAllOracles(priceOracleAddress: string, overrides?: CallOverrides): Promise<void>;

    'setUpAllOracles(address)'(priceOracleAddress: string, overrides?: CallOverrides): Promise<void>;

    setUpChainlinkOracles(priceOracleAddress: string, overrides?: CallOverrides): Promise<void>;

    'setUpChainlinkOracles(address)'(priceOracleAddress: string, overrides?: CallOverrides): Promise<void>;

    setUpUniswapOracles(priceOracleAddress: string, overrides?: CallOverrides): Promise<void>;

    'setUpUniswapOracles(address)'(priceOracleAddress: string, overrides?: CallOverrides): Promise<void>;

    setUp_USDC_ETH_oracles(priceOracleAddress: string, overrides?: CallOverrides): Promise<void>;

    'setUp_USDC_ETH_oracles(address)'(priceOracleAddress: string, overrides?: CallOverrides): Promise<void>;

    transferOwnership(_contract: string, _to: string, overrides?: CallOverrides): Promise<void>;

    'transferOwnership(address,address)'(_contract: string, _to: string, overrides?: CallOverrides): Promise<void>;

    transferToken(token: string, recipient: string, amount: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'transferToken(address,address,uint256)'(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateProtocolFeeFraction(creditLine: string, protocolFee: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'updateProtocolFeeFraction(address,uint256)'(creditLine: string, protocolFee: BigNumberish, overrides?: CallOverrides): Promise<void>;

    verifyUser(_user: string, _verifier: string, overrides?: CallOverrides): Promise<void>;

    'verifyUser(address,address)'(_user: string, _verifier: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addAggregator(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'addAggregator(address,address,address)'(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addSavingsAccountStrategy(
      _strategyRegistry: string,
      _strategyAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'addSavingsAccountStrategy(address,address)'(
      _strategyRegistry: string,
      _strategyAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addTokenAddressForCompoundYield(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'addTokenAddressForCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addVerifier(_verification: string, _verifier: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'addVerifier(address,address)'(
      _verification: string,
      _verifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeImplementationAddressOfProxy(
      proxy: string,
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'changeImplementationAddressOfProxy(address,address)'(
      proxy: string,
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployCompoundYield(
      _admin: string,
      _savingsAccount: string,
      _mockWETH: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'deployCompoundYield(address,address,address,address)'(
      _admin: string,
      _savingsAccount: string,
      _mockWETH: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployMockAdminVerifier(
      arg0: string,
      _verification: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'deployMockAdminVerifier(address,address)'(
      arg0: string,
      _verification: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployMockCToken(
      _mockToken: string,
      _compoundYield: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'deployMockCToken(address,address)'(
      _mockToken: string,
      _compoundYield: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployNoYield(
      _admin: string,
      _savingsAccount: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'deployNoYield(address,address,address)'(
      _admin: string,
      _savingsAccount: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployPriceOracle(
      _admin: string,
      _weth: string,
      _uniswapPriceAvgPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'deployPriceOracle(address,address,uint32)'(
      _admin: string,
      _weth: string,
      _uniswapPriceAvgPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deploySavingsAccount(
      arg0: string,
      _strategyRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'deploySavingsAccount(address,address)'(
      arg0: string,
      _strategyRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployStrategyRegistry(
      arg0: string,
      _maxStrategies: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'deployStrategyRegistry(address,uint256)'(
      arg0: string,
      _maxStrategies: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployVerification(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'deployVerification(address)'(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    emergencyWithdrawFromCompoundYield(
      yield: string,
      _asset: string,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'emergencyWithdrawFromCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    emergencyWithdrawFromNoYield(
      yield: string,
      _asset: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'emergencyWithdrawFromNoYield(address,address,uint256)'(
      yield: string,
      _asset: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    execute(
      target: string,
      value: BigNumberish,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'execute(address,uint256,bytes)'(
      target: string,
      value: BigNumberish,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeFuncSig(
      target: string,
      value: BigNumberish,
      signature: string,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'executeFuncSig(address,uint256,string,bytes)'(
      target: string,
      value: BigNumberish,
      signature: string,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    forceUpdateTokenAddressForCompoundYield(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'forceUpdateTokenAddressForCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getFunctionSignature(signature: string, overrides?: CallOverrides): Promise<BigNumber>;

    'getFunctionSignature(string)'(signature: string, overrides?: CallOverrides): Promise<BigNumber>;

    getImplementationAddressOfProxy(
      sublimeProxyInstance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'getImplementationAddressOfProxy(address)'(
      sublimeProxyInstance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initSavingsAccount(
      savingsAccount: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'initSavingsAccount(address,address)'(
      savingsAccount: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setChainlinkFeedAddress(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'setChainlinkFeedAddress(address,address,address)'(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDepositLimitForCompoundYield(
      _compound: string,
      _asset: string,
      _limit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'setDepositLimitForCompoundYield(address,address,uint256)'(
      _compound: string,
      _asset: string,
      _limit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUpAllOracles(priceOracleAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'setUpAllOracles(address)'(priceOracleAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    setUpChainlinkOracles(priceOracleAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'setUpChainlinkOracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUpUniswapOracles(priceOracleAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'setUpUniswapOracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUp_USDC_ETH_oracles(priceOracleAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'setUp_USDC_ETH_oracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(_contract: string, _to: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'transferOwnership(address,address)'(
      _contract: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferToken(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'transferToken(address,address,uint256)'(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateProtocolFeeFraction(
      creditLine: string,
      protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'updateProtocolFeeFraction(address,uint256)'(
      creditLine: string,
      protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    verifyUser(_user: string, _verifier: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'verifyUser(address,address)'(
      _user: string,
      _verifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addAggregator(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'addAggregator(address,address,address)'(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addSavingsAccountStrategy(
      _strategyRegistry: string,
      _strategyAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'addSavingsAccountStrategy(address,address)'(
      _strategyRegistry: string,
      _strategyAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addTokenAddressForCompoundYield(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'addTokenAddressForCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addVerifier(
      _verification: string,
      _verifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'addVerifier(address,address)'(
      _verification: string,
      _verifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeImplementationAddressOfProxy(
      proxy: string,
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'changeImplementationAddressOfProxy(address,address)'(
      proxy: string,
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployCompoundYield(
      _admin: string,
      _savingsAccount: string,
      _mockWETH: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'deployCompoundYield(address,address,address,address)'(
      _admin: string,
      _savingsAccount: string,
      _mockWETH: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployMockAdminVerifier(
      arg0: string,
      _verification: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'deployMockAdminVerifier(address,address)'(
      arg0: string,
      _verification: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployMockCToken(
      _mockToken: string,
      _compoundYield: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'deployMockCToken(address,address)'(
      _mockToken: string,
      _compoundYield: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployNoYield(
      _admin: string,
      _savingsAccount: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'deployNoYield(address,address,address)'(
      _admin: string,
      _savingsAccount: string,
      _treasury: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployPriceOracle(
      _admin: string,
      _weth: string,
      _uniswapPriceAvgPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'deployPriceOracle(address,address,uint32)'(
      _admin: string,
      _weth: string,
      _uniswapPriceAvgPeriod: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deploySavingsAccount(
      arg0: string,
      _strategyRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'deploySavingsAccount(address,address)'(
      arg0: string,
      _strategyRegistry: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployStrategyRegistry(
      arg0: string,
      _maxStrategies: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'deployStrategyRegistry(address,uint256)'(
      arg0: string,
      _maxStrategies: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployVerification(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'deployVerification(address)'(arg0: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    emergencyWithdrawFromCompoundYield(
      yield: string,
      _asset: string,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'emergencyWithdrawFromCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _wallet: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    emergencyWithdrawFromNoYield(
      yield: string,
      _asset: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'emergencyWithdrawFromNoYield(address,address,uint256)'(
      yield: string,
      _asset: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    execute(
      target: string,
      value: BigNumberish,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'execute(address,uint256,bytes)'(
      target: string,
      value: BigNumberish,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeFuncSig(
      target: string,
      value: BigNumberish,
      signature: string,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'executeFuncSig(address,uint256,string,bytes)'(
      target: string,
      value: BigNumberish,
      signature: string,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    forceUpdateTokenAddressForCompoundYield(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'forceUpdateTokenAddressForCompoundYield(address,address,address)'(
      yield: string,
      _asset: string,
      _liquidityToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getFunctionSignature(signature: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'getFunctionSignature(string)'(signature: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getImplementationAddressOfProxy(
      sublimeProxyInstance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'getImplementationAddressOfProxy(address)'(
      sublimeProxyInstance: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initSavingsAccount(
      savingsAccount: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'initSavingsAccount(address,address)'(
      savingsAccount: string,
      _owner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setChainlinkFeedAddress(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'setChainlinkFeedAddress(address,address,address)'(
      priceOracle: string,
      token: string,
      aggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDepositLimitForCompoundYield(
      _compound: string,
      _asset: string,
      _limit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'setDepositLimitForCompoundYield(address,address,uint256)'(
      _compound: string,
      _asset: string,
      _limit: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUpAllOracles(priceOracleAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'setUpAllOracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUpChainlinkOracles(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'setUpChainlinkOracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUpUniswapOracles(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'setUpUniswapOracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUp_USDC_ETH_oracles(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'setUp_USDC_ETH_oracles(address)'(
      priceOracleAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      _contract: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'transferOwnership(address,address)'(
      _contract: string,
      _to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferToken(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'transferToken(address,address,uint256)'(
      token: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateProtocolFeeFraction(
      creditLine: string,
      protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'updateProtocolFeeFraction(address,uint256)'(
      creditLine: string,
      protocolFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    verifyUser(
      _user: string,
      _verifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'verifyUser(address,address)'(
      _user: string,
      _verifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
