/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface ICEtherInterface extends ethers.utils.Interface {
  functions: {
    'getCash()': FunctionFragment;
    'mint()': FunctionFragment;
    'redeem(uint256)': FunctionFragment;
    'supplyRatePerBlock()': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'getCash', values?: undefined): string;
  encodeFunctionData(functionFragment: 'mint', values?: undefined): string;
  encodeFunctionData(functionFragment: 'redeem', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'supplyRatePerBlock', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'getCash', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'supplyRatePerBlock', data: BytesLike): Result;

  events: {};
}

export class ICEther extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ICEtherInterface;

  functions: {
    getCash(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'getCash()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    mint(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'mint()'(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    redeem(redeemTokens: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'redeem(uint256)'(
      redeemTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supplyRatePerBlock(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'supplyRatePerBlock()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;
  };

  getCash(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'getCash()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  mint(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'mint()'(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  redeem(redeemTokens: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'redeem(uint256)'(redeemTokens: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  supplyRatePerBlock(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'supplyRatePerBlock()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  callStatic: {
    getCash(overrides?: CallOverrides): Promise<BigNumber>;

    'getCash()'(overrides?: CallOverrides): Promise<BigNumber>;

    mint(overrides?: CallOverrides): Promise<void>;

    'mint()'(overrides?: CallOverrides): Promise<void>;

    redeem(redeemTokens: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    'redeem(uint256)'(redeemTokens: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    supplyRatePerBlock(overrides?: CallOverrides): Promise<BigNumber>;

    'supplyRatePerBlock()'(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getCash(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'getCash()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    mint(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'mint()'(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    redeem(redeemTokens: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'redeem(uint256)'(redeemTokens: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    supplyRatePerBlock(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'supplyRatePerBlock()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;
  };

  populateTransaction: {
    getCash(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'getCash()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    mint(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'mint()'(overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    redeem(redeemTokens: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'redeem(uint256)'(
      redeemTokens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supplyRatePerBlock(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'supplyRatePerBlock()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;
  };
}
