/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface PCLParentInterface extends ethers.utils.Interface {
  functions: {
    'IS_TEST()': FunctionFragment;
    'admin()': FunctionFragment;
    'borrowAsset()': FunctionFragment;
    'borrowAssetMockAggregator()': FunctionFragment;
    'borrowCTokenAddress()': FunctionFragment;
    'borrower()': FunctionFragment;
    'collateralAsset()': FunctionFragment;
    'collateralAssetMockAggregator()': FunctionFragment;
    'collateralCTokenAddress()': FunctionFragment;
    'compoundYieldAddress()': FunctionFragment;
    'createMultipleLenders(uint256,uint256,uint128,address)': FunctionFragment;
    'createlender(uint256,uint256,address)': FunctionFragment;
    'failed()': FunctionFragment;
    'goToActiveStage(uint256,uint128)': FunctionFragment;
    'lenderPoolAddress()': FunctionFragment;
    'lenders(uint256)': FunctionFragment;
    'mockAdminVerifier1()': FunctionFragment;
    'mockAdminVerifier2()': FunctionFragment;
    'mockUSDC()': FunctionFragment;
    'mockWETH()': FunctionFragment;
    'noYieldAddress()': FunctionFragment;
    'pooledCreditLineAddress()': FunctionFragment;
    'priceOracleAddress()': FunctionFragment;
    'protocolFeeCollectorAddress()': FunctionFragment;
    'proxyAdmin()': FunctionFragment;
    'randomAmountToLend(uint256,uint256)': FunctionFragment;
    'resetLenders(uint256)': FunctionFragment;
    'savingsAccountAddress()': FunctionFragment;
    'setUp()': FunctionFragment;
    'strategyRegistryAddress()': FunctionFragment;
    'usdcMockAggregator()': FunctionFragment;
    'verificationAddress()': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'IS_TEST', values?: undefined): string;
  encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
  encodeFunctionData(functionFragment: 'borrowAsset', values?: undefined): string;
  encodeFunctionData(functionFragment: 'borrowAssetMockAggregator', values?: undefined): string;
  encodeFunctionData(functionFragment: 'borrowCTokenAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'borrower', values?: undefined): string;
  encodeFunctionData(functionFragment: 'collateralAsset', values?: undefined): string;
  encodeFunctionData(functionFragment: 'collateralAssetMockAggregator', values?: undefined): string;
  encodeFunctionData(functionFragment: 'collateralCTokenAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'compoundYieldAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'createMultipleLenders', values: [BigNumberish, BigNumberish, BigNumberish, string]): string;
  encodeFunctionData(functionFragment: 'createlender', values: [BigNumberish, BigNumberish, string]): string;
  encodeFunctionData(functionFragment: 'failed', values?: undefined): string;
  encodeFunctionData(functionFragment: 'goToActiveStage', values: [BigNumberish, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'lenderPoolAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'lenders', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'mockAdminVerifier1', values?: undefined): string;
  encodeFunctionData(functionFragment: 'mockAdminVerifier2', values?: undefined): string;
  encodeFunctionData(functionFragment: 'mockUSDC', values?: undefined): string;
  encodeFunctionData(functionFragment: 'mockWETH', values?: undefined): string;
  encodeFunctionData(functionFragment: 'noYieldAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'pooledCreditLineAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'priceOracleAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'protocolFeeCollectorAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'proxyAdmin', values?: undefined): string;
  encodeFunctionData(functionFragment: 'randomAmountToLend', values: [BigNumberish, BigNumberish]): string;
  encodeFunctionData(functionFragment: 'resetLenders', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'savingsAccountAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'setUp', values?: undefined): string;
  encodeFunctionData(functionFragment: 'strategyRegistryAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'usdcMockAggregator', values?: undefined): string;
  encodeFunctionData(functionFragment: 'verificationAddress', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'IS_TEST', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'borrowAsset', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'borrowAssetMockAggregator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'borrowCTokenAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'borrower', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'collateralAsset', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'collateralAssetMockAggregator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'collateralCTokenAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'compoundYieldAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createMultipleLenders', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'createlender', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'failed', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'goToActiveStage', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'lenderPoolAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'lenders', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mockAdminVerifier1', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mockAdminVerifier2', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mockUSDC', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'mockWETH', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'noYieldAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'pooledCreditLineAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'priceOracleAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'protocolFeeCollectorAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'proxyAdmin', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'randomAmountToLend', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'resetLenders', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'savingsAccountAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setUp', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'strategyRegistryAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'usdcMockAggregator', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'verificationAddress', data: BytesLike): Result;

  events: {
    'log(string)': EventFragment;
    'log_address(address)': EventFragment;
    'log_bytes(bytes)': EventFragment;
    'log_bytes32(bytes32)': EventFragment;
    'log_int(int256)': EventFragment;
    'log_named_address(string,address)': EventFragment;
    'log_named_bytes(string,bytes)': EventFragment;
    'log_named_bytes32(string,bytes32)': EventFragment;
    'log_named_decimal_int(string,int256,uint256)': EventFragment;
    'log_named_decimal_uint(string,uint256,uint256)': EventFragment;
    'log_named_int(string,int256)': EventFragment;
    'log_named_string(string,string)': EventFragment;
    'log_named_uint(string,uint256)': EventFragment;
    'log_string(string)': EventFragment;
    'log_uint(uint256)': EventFragment;
    'logs(bytes)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'log'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_address'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_bytes'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_bytes32'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_int'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_address'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_bytes'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_bytes32'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_decimal_int'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_decimal_uint'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_int'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_string'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_uint'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_string'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_uint'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'logs'): EventFragment;
}

export class PCLParent extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PCLParentInterface;

  functions: {
    IS_TEST(overrides?: CallOverrides): Promise<[boolean]>;

    'IS_TEST()'(overrides?: CallOverrides): Promise<[boolean]>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    'admin()'(overrides?: CallOverrides): Promise<[string]>;

    borrowAsset(overrides?: CallOverrides): Promise<[string]>;

    'borrowAsset()'(overrides?: CallOverrides): Promise<[string]>;

    borrowAssetMockAggregator(overrides?: CallOverrides): Promise<[string]>;

    'borrowAssetMockAggregator()'(overrides?: CallOverrides): Promise<[string]>;

    borrowCTokenAddress(overrides?: CallOverrides): Promise<[string]>;

    'borrowCTokenAddress()'(overrides?: CallOverrides): Promise<[string]>;

    borrower(overrides?: CallOverrides): Promise<[string]>;

    'borrower()'(overrides?: CallOverrides): Promise<[string]>;

    collateralAsset(overrides?: CallOverrides): Promise<[string]>;

    'collateralAsset()'(overrides?: CallOverrides): Promise<[string]>;

    collateralAssetMockAggregator(overrides?: CallOverrides): Promise<[string]>;

    'collateralAssetMockAggregator()'(overrides?: CallOverrides): Promise<[string]>;

    collateralCTokenAddress(overrides?: CallOverrides): Promise<[string]>;

    'collateralCTokenAddress()'(overrides?: CallOverrides): Promise<[string]>;

    compoundYieldAddress(overrides?: CallOverrides): Promise<[string]>;

    'compoundYieldAddress()'(overrides?: CallOverrides): Promise<[string]>;

    createMultipleLenders(
      _pooledCreditLineID: BigNumberish,
      _nLenders: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'createMultipleLenders(uint256,uint256,uint128,address)'(
      _pooledCreditLineID: BigNumberish,
      _nLenders: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createlender(
      _pooledCreditLineID: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'createlender(uint256,uint256,address)'(
      _pooledCreditLineID: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    failed(overrides?: CallOverrides): Promise<[boolean]>;

    'failed()'(overrides?: CallOverrides): Promise<[boolean]>;

    goToActiveStage(
      _numLenders: BigNumberish,
      _amountToLend: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'goToActiveStage(uint256,uint128)'(
      _numLenders: BigNumberish,
      _amountToLend: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    lenderPoolAddress(overrides?: CallOverrides): Promise<[string]>;

    'lenderPoolAddress()'(overrides?: CallOverrides): Promise<[string]>;

    lenders(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string, BigNumber] & { lenderAddress: string; amount: BigNumber }>;

    'lenders(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { lenderAddress: string; amount: BigNumber }>;

    mockAdminVerifier1(overrides?: CallOverrides): Promise<[string]>;

    'mockAdminVerifier1()'(overrides?: CallOverrides): Promise<[string]>;

    mockAdminVerifier2(overrides?: CallOverrides): Promise<[string]>;

    'mockAdminVerifier2()'(overrides?: CallOverrides): Promise<[string]>;

    mockUSDC(overrides?: CallOverrides): Promise<[string]>;

    'mockUSDC()'(overrides?: CallOverrides): Promise<[string]>;

    mockWETH(overrides?: CallOverrides): Promise<[string]>;

    'mockWETH()'(overrides?: CallOverrides): Promise<[string]>;

    noYieldAddress(overrides?: CallOverrides): Promise<[string]>;

    'noYieldAddress()'(overrides?: CallOverrides): Promise<[string]>;

    pooledCreditLineAddress(overrides?: CallOverrides): Promise<[string]>;

    'pooledCreditLineAddress()'(overrides?: CallOverrides): Promise<[string]>;

    priceOracleAddress(overrides?: CallOverrides): Promise<[string]>;

    'priceOracleAddress()'(overrides?: CallOverrides): Promise<[string]>;

    protocolFeeCollectorAddress(overrides?: CallOverrides): Promise<[string]>;

    'protocolFeeCollectorAddress()'(overrides?: CallOverrides): Promise<[string]>;

    proxyAdmin(overrides?: CallOverrides): Promise<[string]>;

    'proxyAdmin()'(overrides?: CallOverrides): Promise<[string]>;

    randomAmountToLend(_seed: BigNumberish, _maxVal: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    'randomAmountToLend(uint256,uint256)'(_seed: BigNumberish, _maxVal: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    resetLenders(_nLenders: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'resetLenders(uint256)'(
      _nLenders: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    savingsAccountAddress(overrides?: CallOverrides): Promise<[string]>;

    'savingsAccountAddress()'(overrides?: CallOverrides): Promise<[string]>;

    setUp(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'setUp()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    strategyRegistryAddress(overrides?: CallOverrides): Promise<[string]>;

    'strategyRegistryAddress()'(overrides?: CallOverrides): Promise<[string]>;

    usdcMockAggregator(overrides?: CallOverrides): Promise<[string]>;

    'usdcMockAggregator()'(overrides?: CallOverrides): Promise<[string]>;

    verificationAddress(overrides?: CallOverrides): Promise<[string]>;

    'verificationAddress()'(overrides?: CallOverrides): Promise<[string]>;
  };

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  'IS_TEST()'(overrides?: CallOverrides): Promise<boolean>;

  admin(overrides?: CallOverrides): Promise<string>;

  'admin()'(overrides?: CallOverrides): Promise<string>;

  borrowAsset(overrides?: CallOverrides): Promise<string>;

  'borrowAsset()'(overrides?: CallOverrides): Promise<string>;

  borrowAssetMockAggregator(overrides?: CallOverrides): Promise<string>;

  'borrowAssetMockAggregator()'(overrides?: CallOverrides): Promise<string>;

  borrowCTokenAddress(overrides?: CallOverrides): Promise<string>;

  'borrowCTokenAddress()'(overrides?: CallOverrides): Promise<string>;

  borrower(overrides?: CallOverrides): Promise<string>;

  'borrower()'(overrides?: CallOverrides): Promise<string>;

  collateralAsset(overrides?: CallOverrides): Promise<string>;

  'collateralAsset()'(overrides?: CallOverrides): Promise<string>;

  collateralAssetMockAggregator(overrides?: CallOverrides): Promise<string>;

  'collateralAssetMockAggregator()'(overrides?: CallOverrides): Promise<string>;

  collateralCTokenAddress(overrides?: CallOverrides): Promise<string>;

  'collateralCTokenAddress()'(overrides?: CallOverrides): Promise<string>;

  compoundYieldAddress(overrides?: CallOverrides): Promise<string>;

  'compoundYieldAddress()'(overrides?: CallOverrides): Promise<string>;

  createMultipleLenders(
    _pooledCreditLineID: BigNumberish,
    _nLenders: BigNumberish,
    _amountToLend: BigNumberish,
    _asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'createMultipleLenders(uint256,uint256,uint128,address)'(
    _pooledCreditLineID: BigNumberish,
    _nLenders: BigNumberish,
    _amountToLend: BigNumberish,
    _asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createlender(
    _pooledCreditLineID: BigNumberish,
    _amountToLend: BigNumberish,
    _asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'createlender(uint256,uint256,address)'(
    _pooledCreditLineID: BigNumberish,
    _amountToLend: BigNumberish,
    _asset: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  failed(overrides?: CallOverrides): Promise<boolean>;

  'failed()'(overrides?: CallOverrides): Promise<boolean>;

  goToActiveStage(
    _numLenders: BigNumberish,
    _amountToLend: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'goToActiveStage(uint256,uint128)'(
    _numLenders: BigNumberish,
    _amountToLend: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  lenderPoolAddress(overrides?: CallOverrides): Promise<string>;

  'lenderPoolAddress()'(overrides?: CallOverrides): Promise<string>;

  lenders(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string, BigNumber] & { lenderAddress: string; amount: BigNumber }>;

  'lenders(uint256)'(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { lenderAddress: string; amount: BigNumber }>;

  mockAdminVerifier1(overrides?: CallOverrides): Promise<string>;

  'mockAdminVerifier1()'(overrides?: CallOverrides): Promise<string>;

  mockAdminVerifier2(overrides?: CallOverrides): Promise<string>;

  'mockAdminVerifier2()'(overrides?: CallOverrides): Promise<string>;

  mockUSDC(overrides?: CallOverrides): Promise<string>;

  'mockUSDC()'(overrides?: CallOverrides): Promise<string>;

  mockWETH(overrides?: CallOverrides): Promise<string>;

  'mockWETH()'(overrides?: CallOverrides): Promise<string>;

  noYieldAddress(overrides?: CallOverrides): Promise<string>;

  'noYieldAddress()'(overrides?: CallOverrides): Promise<string>;

  pooledCreditLineAddress(overrides?: CallOverrides): Promise<string>;

  'pooledCreditLineAddress()'(overrides?: CallOverrides): Promise<string>;

  priceOracleAddress(overrides?: CallOverrides): Promise<string>;

  'priceOracleAddress()'(overrides?: CallOverrides): Promise<string>;

  protocolFeeCollectorAddress(overrides?: CallOverrides): Promise<string>;

  'protocolFeeCollectorAddress()'(overrides?: CallOverrides): Promise<string>;

  proxyAdmin(overrides?: CallOverrides): Promise<string>;

  'proxyAdmin()'(overrides?: CallOverrides): Promise<string>;

  randomAmountToLend(_seed: BigNumberish, _maxVal: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  'randomAmountToLend(uint256,uint256)'(_seed: BigNumberish, _maxVal: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  resetLenders(_nLenders: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'resetLenders(uint256)'(
    _nLenders: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  savingsAccountAddress(overrides?: CallOverrides): Promise<string>;

  'savingsAccountAddress()'(overrides?: CallOverrides): Promise<string>;

  setUp(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'setUp()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  strategyRegistryAddress(overrides?: CallOverrides): Promise<string>;

  'strategyRegistryAddress()'(overrides?: CallOverrides): Promise<string>;

  usdcMockAggregator(overrides?: CallOverrides): Promise<string>;

  'usdcMockAggregator()'(overrides?: CallOverrides): Promise<string>;

  verificationAddress(overrides?: CallOverrides): Promise<string>;

  'verificationAddress()'(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    'IS_TEST()'(overrides?: CallOverrides): Promise<boolean>;

    admin(overrides?: CallOverrides): Promise<string>;

    'admin()'(overrides?: CallOverrides): Promise<string>;

    borrowAsset(overrides?: CallOverrides): Promise<string>;

    'borrowAsset()'(overrides?: CallOverrides): Promise<string>;

    borrowAssetMockAggregator(overrides?: CallOverrides): Promise<string>;

    'borrowAssetMockAggregator()'(overrides?: CallOverrides): Promise<string>;

    borrowCTokenAddress(overrides?: CallOverrides): Promise<string>;

    'borrowCTokenAddress()'(overrides?: CallOverrides): Promise<string>;

    borrower(overrides?: CallOverrides): Promise<string>;

    'borrower()'(overrides?: CallOverrides): Promise<string>;

    collateralAsset(overrides?: CallOverrides): Promise<string>;

    'collateralAsset()'(overrides?: CallOverrides): Promise<string>;

    collateralAssetMockAggregator(overrides?: CallOverrides): Promise<string>;

    'collateralAssetMockAggregator()'(overrides?: CallOverrides): Promise<string>;

    collateralCTokenAddress(overrides?: CallOverrides): Promise<string>;

    'collateralCTokenAddress()'(overrides?: CallOverrides): Promise<string>;

    compoundYieldAddress(overrides?: CallOverrides): Promise<string>;

    'compoundYieldAddress()'(overrides?: CallOverrides): Promise<string>;

    createMultipleLenders(
      _pooledCreditLineID: BigNumberish,
      _nLenders: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    'createMultipleLenders(uint256,uint256,uint128,address)'(
      _pooledCreditLineID: BigNumberish,
      _nLenders: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createlender(
      _pooledCreditLineID: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: CallOverrides
    ): Promise<string>;

    'createlender(uint256,uint256,address)'(
      _pooledCreditLineID: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: CallOverrides
    ): Promise<string>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    'failed()'(overrides?: CallOverrides): Promise<boolean>;

    goToActiveStage(_numLenders: BigNumberish, _amountToLend: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

    'goToActiveStage(uint256,uint128)'(
      _numLenders: BigNumberish,
      _amountToLend: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    lenderPoolAddress(overrides?: CallOverrides): Promise<string>;

    'lenderPoolAddress()'(overrides?: CallOverrides): Promise<string>;

    lenders(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string, BigNumber] & { lenderAddress: string; amount: BigNumber }>;

    'lenders(uint256)'(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { lenderAddress: string; amount: BigNumber }>;

    mockAdminVerifier1(overrides?: CallOverrides): Promise<string>;

    'mockAdminVerifier1()'(overrides?: CallOverrides): Promise<string>;

    mockAdminVerifier2(overrides?: CallOverrides): Promise<string>;

    'mockAdminVerifier2()'(overrides?: CallOverrides): Promise<string>;

    mockUSDC(overrides?: CallOverrides): Promise<string>;

    'mockUSDC()'(overrides?: CallOverrides): Promise<string>;

    mockWETH(overrides?: CallOverrides): Promise<string>;

    'mockWETH()'(overrides?: CallOverrides): Promise<string>;

    noYieldAddress(overrides?: CallOverrides): Promise<string>;

    'noYieldAddress()'(overrides?: CallOverrides): Promise<string>;

    pooledCreditLineAddress(overrides?: CallOverrides): Promise<string>;

    'pooledCreditLineAddress()'(overrides?: CallOverrides): Promise<string>;

    priceOracleAddress(overrides?: CallOverrides): Promise<string>;

    'priceOracleAddress()'(overrides?: CallOverrides): Promise<string>;

    protocolFeeCollectorAddress(overrides?: CallOverrides): Promise<string>;

    'protocolFeeCollectorAddress()'(overrides?: CallOverrides): Promise<string>;

    proxyAdmin(overrides?: CallOverrides): Promise<string>;

    'proxyAdmin()'(overrides?: CallOverrides): Promise<string>;

    randomAmountToLend(_seed: BigNumberish, _maxVal: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    'randomAmountToLend(uint256,uint256)'(_seed: BigNumberish, _maxVal: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    resetLenders(_nLenders: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'resetLenders(uint256)'(_nLenders: BigNumberish, overrides?: CallOverrides): Promise<void>;

    savingsAccountAddress(overrides?: CallOverrides): Promise<string>;

    'savingsAccountAddress()'(overrides?: CallOverrides): Promise<string>;

    setUp(overrides?: CallOverrides): Promise<void>;

    'setUp()'(overrides?: CallOverrides): Promise<void>;

    strategyRegistryAddress(overrides?: CallOverrides): Promise<string>;

    'strategyRegistryAddress()'(overrides?: CallOverrides): Promise<string>;

    usdcMockAggregator(overrides?: CallOverrides): Promise<string>;

    'usdcMockAggregator()'(overrides?: CallOverrides): Promise<string>;

    verificationAddress(overrides?: CallOverrides): Promise<string>;

    'verificationAddress()'(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    log(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_address(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_bytes(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_bytes32(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_int(undefined: null): TypedEventFilter<[BigNumber], { arg0: BigNumber }>;

    log_named_address(key: null, val: null): TypedEventFilter<[string, string], { key: string; val: string }>;

    log_named_bytes(key: null, val: null): TypedEventFilter<[string, string], { key: string; val: string }>;

    log_named_bytes32(key: null, val: null): TypedEventFilter<[string, string], { key: string; val: string }>;

    log_named_decimal_int(
      key: null,
      val: null,
      decimals: null
    ): TypedEventFilter<[string, BigNumber, BigNumber], { key: string; val: BigNumber; decimals: BigNumber }>;

    log_named_decimal_uint(
      key: null,
      val: null,
      decimals: null
    ): TypedEventFilter<[string, BigNumber, BigNumber], { key: string; val: BigNumber; decimals: BigNumber }>;

    log_named_int(key: null, val: null): TypedEventFilter<[string, BigNumber], { key: string; val: BigNumber }>;

    log_named_string(key: null, val: null): TypedEventFilter<[string, string], { key: string; val: string }>;

    log_named_uint(key: null, val: null): TypedEventFilter<[string, BigNumber], { key: string; val: BigNumber }>;

    log_string(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_uint(undefined: null): TypedEventFilter<[BigNumber], { arg0: BigNumber }>;

    logs(undefined: null): TypedEventFilter<[string], { arg0: string }>;
  };

  estimateGas: {
    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    'IS_TEST()'(overrides?: CallOverrides): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    'admin()'(overrides?: CallOverrides): Promise<BigNumber>;

    borrowAsset(overrides?: CallOverrides): Promise<BigNumber>;

    'borrowAsset()'(overrides?: CallOverrides): Promise<BigNumber>;

    borrowAssetMockAggregator(overrides?: CallOverrides): Promise<BigNumber>;

    'borrowAssetMockAggregator()'(overrides?: CallOverrides): Promise<BigNumber>;

    borrowCTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'borrowCTokenAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    borrower(overrides?: CallOverrides): Promise<BigNumber>;

    'borrower()'(overrides?: CallOverrides): Promise<BigNumber>;

    collateralAsset(overrides?: CallOverrides): Promise<BigNumber>;

    'collateralAsset()'(overrides?: CallOverrides): Promise<BigNumber>;

    collateralAssetMockAggregator(overrides?: CallOverrides): Promise<BigNumber>;

    'collateralAssetMockAggregator()'(overrides?: CallOverrides): Promise<BigNumber>;

    collateralCTokenAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'collateralCTokenAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    compoundYieldAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'compoundYieldAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    createMultipleLenders(
      _pooledCreditLineID: BigNumberish,
      _nLenders: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'createMultipleLenders(uint256,uint256,uint128,address)'(
      _pooledCreditLineID: BigNumberish,
      _nLenders: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createlender(
      _pooledCreditLineID: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'createlender(uint256,uint256,address)'(
      _pooledCreditLineID: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    failed(overrides?: CallOverrides): Promise<BigNumber>;

    'failed()'(overrides?: CallOverrides): Promise<BigNumber>;

    goToActiveStage(
      _numLenders: BigNumberish,
      _amountToLend: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'goToActiveStage(uint256,uint128)'(
      _numLenders: BigNumberish,
      _amountToLend: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    lenderPoolAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'lenderPoolAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    lenders(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    'lenders(uint256)'(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    mockAdminVerifier1(overrides?: CallOverrides): Promise<BigNumber>;

    'mockAdminVerifier1()'(overrides?: CallOverrides): Promise<BigNumber>;

    mockAdminVerifier2(overrides?: CallOverrides): Promise<BigNumber>;

    'mockAdminVerifier2()'(overrides?: CallOverrides): Promise<BigNumber>;

    mockUSDC(overrides?: CallOverrides): Promise<BigNumber>;

    'mockUSDC()'(overrides?: CallOverrides): Promise<BigNumber>;

    mockWETH(overrides?: CallOverrides): Promise<BigNumber>;

    'mockWETH()'(overrides?: CallOverrides): Promise<BigNumber>;

    noYieldAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'noYieldAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    pooledCreditLineAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'pooledCreditLineAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    priceOracleAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'priceOracleAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeCollectorAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'protocolFeeCollectorAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    proxyAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    'proxyAdmin()'(overrides?: CallOverrides): Promise<BigNumber>;

    randomAmountToLend(_seed: BigNumberish, _maxVal: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    'randomAmountToLend(uint256,uint256)'(_seed: BigNumberish, _maxVal: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    resetLenders(_nLenders: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'resetLenders(uint256)'(_nLenders: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    savingsAccountAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'savingsAccountAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    setUp(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'setUp()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    strategyRegistryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'strategyRegistryAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    usdcMockAggregator(overrides?: CallOverrides): Promise<BigNumber>;

    'usdcMockAggregator()'(overrides?: CallOverrides): Promise<BigNumber>;

    verificationAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'verificationAddress()'(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'IS_TEST()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'admin()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrowAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'borrowAsset()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrowAssetMockAggregator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'borrowAssetMockAggregator()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrowCTokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'borrowCTokenAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrower(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'borrower()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collateralAsset(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'collateralAsset()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collateralAssetMockAggregator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'collateralAssetMockAggregator()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    collateralCTokenAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'collateralCTokenAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    compoundYieldAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'compoundYieldAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    createMultipleLenders(
      _pooledCreditLineID: BigNumberish,
      _nLenders: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'createMultipleLenders(uint256,uint256,uint128,address)'(
      _pooledCreditLineID: BigNumberish,
      _nLenders: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createlender(
      _pooledCreditLineID: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'createlender(uint256,uint256,address)'(
      _pooledCreditLineID: BigNumberish,
      _amountToLend: BigNumberish,
      _asset: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    failed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'failed()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    goToActiveStage(
      _numLenders: BigNumberish,
      _amountToLend: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'goToActiveStage(uint256,uint128)'(
      _numLenders: BigNumberish,
      _amountToLend: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    lenderPoolAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'lenderPoolAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lenders(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'lenders(uint256)'(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mockAdminVerifier1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'mockAdminVerifier1()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mockAdminVerifier2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'mockAdminVerifier2()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mockUSDC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'mockUSDC()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mockWETH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'mockWETH()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    noYieldAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'noYieldAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pooledCreditLineAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'pooledCreditLineAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceOracleAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'priceOracleAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeCollectorAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'protocolFeeCollectorAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxyAdmin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'proxyAdmin()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    randomAmountToLend(_seed: BigNumberish, _maxVal: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'randomAmountToLend(uint256,uint256)'(
      _seed: BigNumberish,
      _maxVal: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    resetLenders(_nLenders: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'resetLenders(uint256)'(
      _nLenders: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    savingsAccountAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'savingsAccountAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUp(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'setUp()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    strategyRegistryAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'strategyRegistryAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    usdcMockAggregator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'usdcMockAggregator()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    verificationAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'verificationAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
