/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface PoolEthUtilsInterface extends ethers.utils.Interface {
  functions: {
    'addEthCollateralInMarginCall(address,address)': FunctionFragment;
    'depositEthAsCollateralToPool(address)': FunctionFragment;
    'ethLend(address,address,address)': FunctionFragment;
    'weth()': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'addEthCollateralInMarginCall', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'depositEthAsCollateralToPool', values: [string]): string;
  encodeFunctionData(functionFragment: 'ethLend', values: [string, string, string]): string;
  encodeFunctionData(functionFragment: 'weth', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'addEthCollateralInMarginCall', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'depositEthAsCollateralToPool', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'ethLend', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'weth', data: BytesLike): Result;

  events: {};
}

export class PoolEthUtils extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PoolEthUtilsInterface;

  functions: {
    addEthCollateralInMarginCall(
      _pool: string,
      _lender: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'addEthCollateralInMarginCall(address,address)'(
      _pool: string,
      _lender: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    depositEthAsCollateralToPool(
      _pool: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'depositEthAsCollateralToPool(address)'(
      _pool: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ethLend(
      _pool: string,
      _lender: string,
      _strategy: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'ethLend(address,address,address)'(
      _pool: string,
      _lender: string,
      _strategy: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    weth(overrides?: CallOverrides): Promise<[string]>;

    'weth()'(overrides?: CallOverrides): Promise<[string]>;
  };

  addEthCollateralInMarginCall(
    _pool: string,
    _lender: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'addEthCollateralInMarginCall(address,address)'(
    _pool: string,
    _lender: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  depositEthAsCollateralToPool(
    _pool: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'depositEthAsCollateralToPool(address)'(
    _pool: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ethLend(
    _pool: string,
    _lender: string,
    _strategy: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'ethLend(address,address,address)'(
    _pool: string,
    _lender: string,
    _strategy: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  weth(overrides?: CallOverrides): Promise<string>;

  'weth()'(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addEthCollateralInMarginCall(_pool: string, _lender: string, overrides?: CallOverrides): Promise<void>;

    'addEthCollateralInMarginCall(address,address)'(_pool: string, _lender: string, overrides?: CallOverrides): Promise<void>;

    depositEthAsCollateralToPool(_pool: string, overrides?: CallOverrides): Promise<void>;

    'depositEthAsCollateralToPool(address)'(_pool: string, overrides?: CallOverrides): Promise<void>;

    ethLend(_pool: string, _lender: string, _strategy: string, overrides?: CallOverrides): Promise<void>;

    'ethLend(address,address,address)'(_pool: string, _lender: string, _strategy: string, overrides?: CallOverrides): Promise<void>;

    weth(overrides?: CallOverrides): Promise<string>;

    'weth()'(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addEthCollateralInMarginCall(
      _pool: string,
      _lender: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'addEthCollateralInMarginCall(address,address)'(
      _pool: string,
      _lender: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    depositEthAsCollateralToPool(_pool: string, overrides?: PayableOverrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'depositEthAsCollateralToPool(address)'(
      _pool: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ethLend(
      _pool: string,
      _lender: string,
      _strategy: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'ethLend(address,address,address)'(
      _pool: string,
      _lender: string,
      _strategy: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    weth(overrides?: CallOverrides): Promise<BigNumber>;

    'weth()'(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addEthCollateralInMarginCall(
      _pool: string,
      _lender: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'addEthCollateralInMarginCall(address,address)'(
      _pool: string,
      _lender: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    depositEthAsCollateralToPool(
      _pool: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'depositEthAsCollateralToPool(address)'(
      _pool: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ethLend(
      _pool: string,
      _lender: string,
      _strategy: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'ethLend(address,address,address)'(
      _pool: string,
      _lender: string,
      _strategy: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    weth(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'weth()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
