/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface PriceOracleTestsInterface extends ethers.utils.Interface {
  functions: {
    'IS_TEST()': FunctionFragment;
    'failed()': FunctionFragment;
    'setUp()': FunctionFragment;
    'test_deployments()': FunctionFragment;
    'test_getChainlinkLatestPrice()': FunctionFragment;
    'test_getChainlinkLatestPriceWithArgs(address,address)': FunctionFragment;
    'test_setUniswapPriceAveragingPeriod()': FunctionFragment;
    'test_should_fetch_latestPrice_from_chainlink()': FunctionFragment;
    'test_should_fetch_latestPrice_from_uniswap()': FunctionFragment;
    'test_uniswapPrice(address,address)': FunctionFragment;
    'test_uniswapPrice1()': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'IS_TEST', values?: undefined): string;
  encodeFunctionData(functionFragment: 'failed', values?: undefined): string;
  encodeFunctionData(functionFragment: 'setUp', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test_deployments', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test_getChainlinkLatestPrice', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test_getChainlinkLatestPriceWithArgs', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'test_setUniswapPriceAveragingPeriod', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test_should_fetch_latestPrice_from_chainlink', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test_should_fetch_latestPrice_from_uniswap', values?: undefined): string;
  encodeFunctionData(functionFragment: 'test_uniswapPrice', values: [string, string]): string;
  encodeFunctionData(functionFragment: 'test_uniswapPrice1', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'IS_TEST', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'failed', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setUp', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test_deployments', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test_getChainlinkLatestPrice', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test_getChainlinkLatestPriceWithArgs', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test_setUniswapPriceAveragingPeriod', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test_should_fetch_latestPrice_from_chainlink', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test_should_fetch_latestPrice_from_uniswap', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test_uniswapPrice', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'test_uniswapPrice1', data: BytesLike): Result;

  events: {
    'log(string)': EventFragment;
    'log_address(address)': EventFragment;
    'log_bytes(bytes)': EventFragment;
    'log_bytes32(bytes32)': EventFragment;
    'log_int(int256)': EventFragment;
    'log_named_address(string,address)': EventFragment;
    'log_named_bytes(string,bytes)': EventFragment;
    'log_named_bytes32(string,bytes32)': EventFragment;
    'log_named_decimal_int(string,int256,uint256)': EventFragment;
    'log_named_decimal_uint(string,uint256,uint256)': EventFragment;
    'log_named_int(string,int256)': EventFragment;
    'log_named_string(string,string)': EventFragment;
    'log_named_uint(string,uint256)': EventFragment;
    'log_string(string)': EventFragment;
    'log_uint(uint256)': EventFragment;
    'logs(bytes)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'log'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_address'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_bytes'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_bytes32'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_int'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_address'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_bytes'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_bytes32'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_decimal_int'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_decimal_uint'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_int'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_string'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_named_uint'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_string'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'log_uint'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'logs'): EventFragment;
}

export class PriceOracleTests extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PriceOracleTestsInterface;

  functions: {
    IS_TEST(overrides?: CallOverrides): Promise<[boolean]>;

    'IS_TEST()'(overrides?: CallOverrides): Promise<[boolean]>;

    failed(overrides?: CallOverrides): Promise<[boolean]>;

    'failed()'(overrides?: CallOverrides): Promise<[boolean]>;

    setUp(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'setUp()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    test_deployments(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'test_deployments()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    test_getChainlinkLatestPrice(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'test_getChainlinkLatestPrice()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    test_getChainlinkLatestPriceWithArgs(
      num: string,
      den: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'test_getChainlinkLatestPriceWithArgs(address,address)'(
      num: string,
      den: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_setUniswapPriceAveragingPeriod(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'test_setUniswapPriceAveragingPeriod()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    test_should_fetch_latestPrice_from_chainlink(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'test_should_fetch_latestPrice_from_chainlink()'(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_should_fetch_latestPrice_from_uniswap(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'test_should_fetch_latestPrice_from_uniswap()'(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_uniswapPrice(num: string, den: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'test_uniswapPrice(address,address)'(
      num: string,
      den: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    test_uniswapPrice1(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'test_uniswapPrice1()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;
  };

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  'IS_TEST()'(overrides?: CallOverrides): Promise<boolean>;

  failed(overrides?: CallOverrides): Promise<boolean>;

  'failed()'(overrides?: CallOverrides): Promise<boolean>;

  setUp(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'setUp()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  test_deployments(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'test_deployments()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  test_getChainlinkLatestPrice(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'test_getChainlinkLatestPrice()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  test_getChainlinkLatestPriceWithArgs(
    num: string,
    den: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'test_getChainlinkLatestPriceWithArgs(address,address)'(
    num: string,
    den: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  test_setUniswapPriceAveragingPeriod(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'test_setUniswapPriceAveragingPeriod()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  test_should_fetch_latestPrice_from_chainlink(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'test_should_fetch_latestPrice_from_chainlink()'(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  test_should_fetch_latestPrice_from_uniswap(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'test_should_fetch_latestPrice_from_uniswap()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  test_uniswapPrice(num: string, den: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'test_uniswapPrice(address,address)'(
    num: string,
    den: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  test_uniswapPrice1(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'test_uniswapPrice1()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  callStatic: {
    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    'IS_TEST()'(overrides?: CallOverrides): Promise<boolean>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    'failed()'(overrides?: CallOverrides): Promise<boolean>;

    setUp(overrides?: CallOverrides): Promise<void>;

    'setUp()'(overrides?: CallOverrides): Promise<void>;

    test_deployments(overrides?: CallOverrides): Promise<void>;

    'test_deployments()'(overrides?: CallOverrides): Promise<void>;

    test_getChainlinkLatestPrice(overrides?: CallOverrides): Promise<void>;

    'test_getChainlinkLatestPrice()'(overrides?: CallOverrides): Promise<void>;

    test_getChainlinkLatestPriceWithArgs(num: string, den: string, overrides?: CallOverrides): Promise<void>;

    'test_getChainlinkLatestPriceWithArgs(address,address)'(num: string, den: string, overrides?: CallOverrides): Promise<void>;

    test_setUniswapPriceAveragingPeriod(overrides?: CallOverrides): Promise<void>;

    'test_setUniswapPriceAveragingPeriod()'(overrides?: CallOverrides): Promise<void>;

    test_should_fetch_latestPrice_from_chainlink(overrides?: CallOverrides): Promise<void>;

    'test_should_fetch_latestPrice_from_chainlink()'(overrides?: CallOverrides): Promise<void>;

    test_should_fetch_latestPrice_from_uniswap(overrides?: CallOverrides): Promise<void>;

    'test_should_fetch_latestPrice_from_uniswap()'(overrides?: CallOverrides): Promise<void>;

    test_uniswapPrice(num: string, den: string, overrides?: CallOverrides): Promise<void>;

    'test_uniswapPrice(address,address)'(num: string, den: string, overrides?: CallOverrides): Promise<void>;

    test_uniswapPrice1(overrides?: CallOverrides): Promise<void>;

    'test_uniswapPrice1()'(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    log(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_address(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_bytes(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_bytes32(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_int(undefined: null): TypedEventFilter<[BigNumber], { arg0: BigNumber }>;

    log_named_address(key: null, val: null): TypedEventFilter<[string, string], { key: string; val: string }>;

    log_named_bytes(key: null, val: null): TypedEventFilter<[string, string], { key: string; val: string }>;

    log_named_bytes32(key: null, val: null): TypedEventFilter<[string, string], { key: string; val: string }>;

    log_named_decimal_int(
      key: null,
      val: null,
      decimals: null
    ): TypedEventFilter<[string, BigNumber, BigNumber], { key: string; val: BigNumber; decimals: BigNumber }>;

    log_named_decimal_uint(
      key: null,
      val: null,
      decimals: null
    ): TypedEventFilter<[string, BigNumber, BigNumber], { key: string; val: BigNumber; decimals: BigNumber }>;

    log_named_int(key: null, val: null): TypedEventFilter<[string, BigNumber], { key: string; val: BigNumber }>;

    log_named_string(key: null, val: null): TypedEventFilter<[string, string], { key: string; val: string }>;

    log_named_uint(key: null, val: null): TypedEventFilter<[string, BigNumber], { key: string; val: BigNumber }>;

    log_string(undefined: null): TypedEventFilter<[string], { arg0: string }>;

    log_uint(undefined: null): TypedEventFilter<[BigNumber], { arg0: BigNumber }>;

    logs(undefined: null): TypedEventFilter<[string], { arg0: string }>;
  };

  estimateGas: {
    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    'IS_TEST()'(overrides?: CallOverrides): Promise<BigNumber>;

    failed(overrides?: CallOverrides): Promise<BigNumber>;

    'failed()'(overrides?: CallOverrides): Promise<BigNumber>;

    setUp(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'setUp()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test_deployments(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'test_deployments()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test_getChainlinkLatestPrice(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'test_getChainlinkLatestPrice()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test_getChainlinkLatestPriceWithArgs(
      num: string,
      den: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'test_getChainlinkLatestPriceWithArgs(address,address)'(
      num: string,
      den: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    test_setUniswapPriceAveragingPeriod(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'test_setUniswapPriceAveragingPeriod()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test_should_fetch_latestPrice_from_chainlink(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'test_should_fetch_latestPrice_from_chainlink()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test_should_fetch_latestPrice_from_uniswap(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'test_should_fetch_latestPrice_from_uniswap()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    test_uniswapPrice(num: string, den: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'test_uniswapPrice(address,address)'(
      num: string,
      den: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    test_uniswapPrice1(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'test_uniswapPrice1()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'IS_TEST()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    failed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'failed()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setUp(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'setUp()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    test_deployments(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'test_deployments()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    test_getChainlinkLatestPrice(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'test_getChainlinkLatestPrice()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    test_getChainlinkLatestPriceWithArgs(
      num: string,
      den: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'test_getChainlinkLatestPriceWithArgs(address,address)'(
      num: string,
      den: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_setUniswapPriceAveragingPeriod(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'test_setUniswapPriceAveragingPeriod()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    test_should_fetch_latestPrice_from_chainlink(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'test_should_fetch_latestPrice_from_chainlink()'(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_should_fetch_latestPrice_from_uniswap(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'test_should_fetch_latestPrice_from_uniswap()'(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_uniswapPrice(num: string, den: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'test_uniswapPrice(address,address)'(
      num: string,
      den: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    test_uniswapPrice1(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'test_uniswapPrice1()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;
  };
}
