/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import { TypedEventFilter, TypedEvent, TypedListener } from './commons';

interface TwitterVerifierInterface extends ethers.utils.Interface {
  functions: {
    'VERIFICATION()': FunctionFragment;
    'blackListDigest(bytes32)': FunctionFragment;
    'initialize(address,address,uint256,string,string)': FunctionFragment;
    'owner()': FunctionFragment;
    'registerSelf(bool,uint8,bytes32,bytes32,string,string,uint256)': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'signValidity()': FunctionFragment;
    'signerAddress()': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'twitterIdMap(string)': FunctionFragment;
    'unregisterSelf()': FunctionFragment;
    'unregisterUser(address)': FunctionFragment;
    'updateSignValidity(uint256)': FunctionFragment;
    'updateSignerAddress(address)': FunctionFragment;
    'usedTweetIds(string)': FunctionFragment;
    'userData(address)': FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'VERIFICATION', values?: undefined): string;
  encodeFunctionData(functionFragment: 'blackListDigest', values: [BytesLike]): string;
  encodeFunctionData(functionFragment: 'initialize', values: [string, string, BigNumberish, string, string]): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'registerSelf',
    values: [boolean, BigNumberish, BytesLike, BytesLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(functionFragment: 'signValidity', values?: undefined): string;
  encodeFunctionData(functionFragment: 'signerAddress', values?: undefined): string;
  encodeFunctionData(functionFragment: 'transferOwnership', values: [string]): string;
  encodeFunctionData(functionFragment: 'twitterIdMap', values: [string]): string;
  encodeFunctionData(functionFragment: 'unregisterSelf', values?: undefined): string;
  encodeFunctionData(functionFragment: 'unregisterUser', values: [string]): string;
  encodeFunctionData(functionFragment: 'updateSignValidity', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'updateSignerAddress', values: [string]): string;
  encodeFunctionData(functionFragment: 'usedTweetIds', values: [string]): string;
  encodeFunctionData(functionFragment: 'userData', values: [string]): string;

  decodeFunctionResult(functionFragment: 'VERIFICATION', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'blackListDigest', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'registerSelf', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'signValidity', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'signerAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'twitterIdMap', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'unregisterSelf', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'unregisterUser', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'updateSignValidity', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'updateSignerAddress', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'usedTweetIds', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'userData', data: BytesLike): Result;

  events: {
    'OwnershipTransferred(address,address)': EventFragment;
    'SignValidityUpdated(uint256)': EventFragment;
    'SignerUpdated(address)': EventFragment;
    'UserRegistered(address,bool,string)': EventFragment;
    'UserUnregistered(address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'SignValidityUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'SignerUpdated'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'UserRegistered'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'UserUnregistered'): EventFragment;
}

export class TwitterVerifier extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TwitterVerifierInterface;

  functions: {
    VERIFICATION(overrides?: CallOverrides): Promise<[string]>;

    'VERIFICATION()'(overrides?: CallOverrides): Promise<[string]>;

    blackListDigest(_hash: BytesLike, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'blackListDigest(bytes32)'(_hash: BytesLike, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    initialize(
      _admin: string,
      _signerAddress: string,
      _signValidity: BigNumberish,
      _name: string,
      _version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'initialize(address,address,uint256,string,string)'(
      _admin: string,
      _signerAddress: string,
      _signValidity: BigNumberish,
      _name: string,
      _version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    'owner()'(overrides?: CallOverrides): Promise<[string]>;

    registerSelf(
      _isMasterLinked: boolean,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _twitterId: string,
      _tweetId: string,
      _timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'registerSelf(bool,uint8,bytes32,bytes32,string,string,uint256)'(
      _isMasterLinked: boolean,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _twitterId: string,
      _tweetId: string,
      _timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'renounceOwnership()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    signValidity(overrides?: CallOverrides): Promise<[BigNumber]>;

    'signValidity()'(overrides?: CallOverrides): Promise<[BigNumber]>;

    signerAddress(overrides?: CallOverrides): Promise<[string]>;

    'signerAddress()'(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    twitterIdMap(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    'twitterIdMap(string)'(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    unregisterSelf(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'unregisterSelf()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    unregisterUser(_user: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'unregisterUser(address)'(_user: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    updateSignValidity(
      _signValidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    'updateSignValidity(uint256)'(
      _signValidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateSignerAddress(_signerAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

    'updateSignerAddress(address)'(
      _signerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    usedTweetIds(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    'usedTweetIds(string)'(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    userData(arg0: string, overrides?: CallOverrides): Promise<[string, string] & { twitterId: string; tweetId: string }>;

    'userData(address)'(arg0: string, overrides?: CallOverrides): Promise<[string, string] & { twitterId: string; tweetId: string }>;
  };

  VERIFICATION(overrides?: CallOverrides): Promise<string>;

  'VERIFICATION()'(overrides?: CallOverrides): Promise<string>;

  blackListDigest(_hash: BytesLike, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'blackListDigest(bytes32)'(_hash: BytesLike, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  initialize(
    _admin: string,
    _signerAddress: string,
    _signValidity: BigNumberish,
    _name: string,
    _version: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'initialize(address,address,uint256,string,string)'(
    _admin: string,
    _signerAddress: string,
    _signValidity: BigNumberish,
    _name: string,
    _version: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  'owner()'(overrides?: CallOverrides): Promise<string>;

  registerSelf(
    _isMasterLinked: boolean,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _twitterId: string,
    _tweetId: string,
    _timestamp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'registerSelf(bool,uint8,bytes32,bytes32,string,string,uint256)'(
    _isMasterLinked: boolean,
    _v: BigNumberish,
    _r: BytesLike,
    _s: BytesLike,
    _twitterId: string,
    _tweetId: string,
    _timestamp: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'renounceOwnership()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  signValidity(overrides?: CallOverrides): Promise<BigNumber>;

  'signValidity()'(overrides?: CallOverrides): Promise<BigNumber>;

  signerAddress(overrides?: CallOverrides): Promise<string>;

  'signerAddress()'(overrides?: CallOverrides): Promise<string>;

  transferOwnership(newOwner: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'transferOwnership(address)'(newOwner: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  twitterIdMap(arg0: string, overrides?: CallOverrides): Promise<string>;

  'twitterIdMap(string)'(arg0: string, overrides?: CallOverrides): Promise<string>;

  unregisterSelf(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'unregisterSelf()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  unregisterUser(_user: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'unregisterUser(address)'(_user: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  updateSignValidity(
    _signValidity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  'updateSignValidity(uint256)'(
    _signValidity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateSignerAddress(_signerAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<ContractTransaction>;

  'updateSignerAddress(address)'(
    _signerAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  usedTweetIds(arg0: string, overrides?: CallOverrides): Promise<string>;

  'usedTweetIds(string)'(arg0: string, overrides?: CallOverrides): Promise<string>;

  userData(arg0: string, overrides?: CallOverrides): Promise<[string, string] & { twitterId: string; tweetId: string }>;

  'userData(address)'(arg0: string, overrides?: CallOverrides): Promise<[string, string] & { twitterId: string; tweetId: string }>;

  callStatic: {
    VERIFICATION(overrides?: CallOverrides): Promise<string>;

    'VERIFICATION()'(overrides?: CallOverrides): Promise<string>;

    blackListDigest(_hash: BytesLike, overrides?: CallOverrides): Promise<void>;

    'blackListDigest(bytes32)'(_hash: BytesLike, overrides?: CallOverrides): Promise<void>;

    initialize(
      _admin: string,
      _signerAddress: string,
      _signValidity: BigNumberish,
      _name: string,
      _version: string,
      overrides?: CallOverrides
    ): Promise<void>;

    'initialize(address,address,uint256,string,string)'(
      _admin: string,
      _signerAddress: string,
      _signValidity: BigNumberish,
      _name: string,
      _version: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    'owner()'(overrides?: CallOverrides): Promise<string>;

    registerSelf(
      _isMasterLinked: boolean,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _twitterId: string,
      _tweetId: string,
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    'registerSelf(bool,uint8,bytes32,bytes32,string,string,uint256)'(
      _isMasterLinked: boolean,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _twitterId: string,
      _tweetId: string,
      _timestamp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    'renounceOwnership()'(overrides?: CallOverrides): Promise<void>;

    signValidity(overrides?: CallOverrides): Promise<BigNumber>;

    'signValidity()'(overrides?: CallOverrides): Promise<BigNumber>;

    signerAddress(overrides?: CallOverrides): Promise<string>;

    'signerAddress()'(overrides?: CallOverrides): Promise<string>;

    transferOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>;

    'transferOwnership(address)'(newOwner: string, overrides?: CallOverrides): Promise<void>;

    twitterIdMap(arg0: string, overrides?: CallOverrides): Promise<string>;

    'twitterIdMap(string)'(arg0: string, overrides?: CallOverrides): Promise<string>;

    unregisterSelf(overrides?: CallOverrides): Promise<void>;

    'unregisterSelf()'(overrides?: CallOverrides): Promise<void>;

    unregisterUser(_user: string, overrides?: CallOverrides): Promise<void>;

    'unregisterUser(address)'(_user: string, overrides?: CallOverrides): Promise<void>;

    updateSignValidity(_signValidity: BigNumberish, overrides?: CallOverrides): Promise<void>;

    'updateSignValidity(uint256)'(_signValidity: BigNumberish, overrides?: CallOverrides): Promise<void>;

    updateSignerAddress(_signerAddress: string, overrides?: CallOverrides): Promise<void>;

    'updateSignerAddress(address)'(_signerAddress: string, overrides?: CallOverrides): Promise<void>;

    usedTweetIds(arg0: string, overrides?: CallOverrides): Promise<string>;

    'usedTweetIds(string)'(arg0: string, overrides?: CallOverrides): Promise<string>;

    userData(arg0: string, overrides?: CallOverrides): Promise<[string, string] & { twitterId: string; tweetId: string }>;

    'userData(address)'(arg0: string, overrides?: CallOverrides): Promise<[string, string] & { twitterId: string; tweetId: string }>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<[string, string], { previousOwner: string; newOwner: string }>;

    SignValidityUpdated(signValidity: null): TypedEventFilter<[BigNumber], { signValidity: BigNumber }>;

    SignerUpdated(signerAddress: string | null): TypedEventFilter<[string], { signerAddress: string }>;

    UserRegistered(
      user: string | null,
      isMasterLinked: null,
      metadata: string | null
    ): TypedEventFilter<[string, boolean, string], { user: string; isMasterLinked: boolean; metadata: string }>;

    UserUnregistered(user: string | null): TypedEventFilter<[string], { user: string }>;
  };

  estimateGas: {
    VERIFICATION(overrides?: CallOverrides): Promise<BigNumber>;

    'VERIFICATION()'(overrides?: CallOverrides): Promise<BigNumber>;

    blackListDigest(_hash: BytesLike, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'blackListDigest(bytes32)'(_hash: BytesLike, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    initialize(
      _admin: string,
      _signerAddress: string,
      _signValidity: BigNumberish,
      _name: string,
      _version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'initialize(address,address,uint256,string,string)'(
      _admin: string,
      _signerAddress: string,
      _signValidity: BigNumberish,
      _name: string,
      _version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    'owner()'(overrides?: CallOverrides): Promise<BigNumber>;

    registerSelf(
      _isMasterLinked: boolean,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _twitterId: string,
      _tweetId: string,
      _timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    'registerSelf(bool,uint8,bytes32,bytes32,string,string,uint256)'(
      _isMasterLinked: boolean,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _twitterId: string,
      _tweetId: string,
      _timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'renounceOwnership()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    signValidity(overrides?: CallOverrides): Promise<BigNumber>;

    'signValidity()'(overrides?: CallOverrides): Promise<BigNumber>;

    signerAddress(overrides?: CallOverrides): Promise<BigNumber>;

    'signerAddress()'(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'transferOwnership(address)'(newOwner: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    twitterIdMap(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    'twitterIdMap(string)'(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    unregisterSelf(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'unregisterSelf()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    unregisterUser(_user: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'unregisterUser(address)'(_user: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    updateSignValidity(_signValidity: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'updateSignValidity(uint256)'(
      _signValidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateSignerAddress(_signerAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    'updateSignerAddress(address)'(_signerAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

    usedTweetIds(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    'usedTweetIds(string)'(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    userData(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    'userData(address)'(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    VERIFICATION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'VERIFICATION()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    blackListDigest(_hash: BytesLike, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'blackListDigest(bytes32)'(
      _hash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _admin: string,
      _signerAddress: string,
      _signValidity: BigNumberish,
      _name: string,
      _version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'initialize(address,address,uint256,string,string)'(
      _admin: string,
      _signerAddress: string,
      _signValidity: BigNumberish,
      _name: string,
      _version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'owner()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerSelf(
      _isMasterLinked: boolean,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _twitterId: string,
      _tweetId: string,
      _timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'registerSelf(bool,uint8,bytes32,bytes32,string,string,uint256)'(
      _isMasterLinked: boolean,
      _v: BigNumberish,
      _r: BytesLike,
      _s: BytesLike,
      _twitterId: string,
      _tweetId: string,
      _timestamp: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'renounceOwnership()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    signValidity(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'signValidity()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    signerAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'signerAddress()'(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(newOwner: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'transferOwnership(address)'(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    twitterIdMap(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'twitterIdMap(string)'(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    unregisterSelf(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'unregisterSelf()'(overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    unregisterUser(_user: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'unregisterUser(address)'(_user: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    updateSignValidity(
      _signValidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    'updateSignValidity(uint256)'(
      _signValidity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateSignerAddress(_signerAddress: string, overrides?: Overrides & { from?: string | Promise<string> }): Promise<PopulatedTransaction>;

    'updateSignerAddress(address)'(
      _signerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    usedTweetIds(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'usedTweetIds(string)'(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userData(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

    'userData(address)'(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
