/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';

import type { IPool } from '../IPool';

export class IPool__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): IPool {
    return new Contract(address, _abi, signerOrProvider) as IPool;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'protocolFee',
        type: 'uint256',
      },
    ],
    name: 'AmountBorrowed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'borrower',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'sharesReceived',
        type: 'uint256',
      },
    ],
    name: 'CollateralAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'borrower',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'CollateralWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'liquidator',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'lender',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_tokenReceived',
        type: 'uint256',
      },
    ],
    name: 'LenderLiquidated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amountSupplied',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'lenderAddress',
        type: 'address',
      },
    ],
    name: 'LiquiditySupplied',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'lenderAddress',
        type: 'address',
      },
    ],
    name: 'LiquidityWithdrawn',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'borrower',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'lender',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'sharesReceived',
        type: 'uint256',
      },
    ],
    name: 'MarginCallCollateralAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'lenderAddress',
        type: 'address',
      },
    ],
    name: 'MarginCalled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'PoolCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'PoolClosed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'liquidator',
        type: 'address',
      },
    ],
    name: 'PoolLiquidated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [],
    name: 'PoolTerminated',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_lender',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: '_isDirect',
        type: 'bool',
      },
    ],
    name: 'addCollateralInMarginCall',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'borrower',
    outputs: [
      {
        internalType: 'address',
        name: 'poolBorrower',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'closeLoan',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: '_transferFromSavingsAccount',
        type: 'bool',
      },
    ],
    name: 'depositCollateral',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_lender',
        type: 'address',
      },
    ],
    name: 'getBalanceDetails',
    outputs: [
      {
        internalType: 'uint256',
        name: 'lenderPoolTokens',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'totalPoolTokens',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getLoanStatus',
    outputs: [
      {
        internalType: 'uint256',
        name: 'loanStatus',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_lender',
        type: 'address',
      },
    ],
    name: 'getMarginCallEndTime',
    outputs: [
      {
        internalType: 'uint256',
        name: 'marginCallEndTimeForLender',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '_borrowAmountRequested',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_borrowRate',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: '_borrower',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_borrowAsset',
        type: 'address',
      },
      {
        internalType: 'address',
        name: '_collateralAsset',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_idealCollateralRatio',
        type: 'uint256',
      },
      {
        internalType: 'uint64',
        name: '_repaymentInterval',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: '_noOfRepaymentIntervals',
        type: 'uint64',
      },
      {
        internalType: 'address',
        name: '_poolSavingsStrategy',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_collateralAmount',
        type: 'uint256',
      },
      {
        internalType: 'bool',
        name: '_transferFromSavingsAccount',
        type: 'bool',
      },
      {
        internalType: 'address',
        name: '_lenderVerifier',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_loanWithdrawalDuration',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: '_collectionPeriod',
        type: 'uint256',
      },
    ],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_lender',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
      {
        internalType: 'address',
        name: '_strategy',
        type: 'address',
      },
      {
        internalType: 'bool',
        name: '_fromSavingsAccount',
        type: 'bool',
      },
    ],
    name: 'lend',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [
      {
        internalType: 'uint256',
        name: 'totalPoolTokens',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdrawBorrowedAmount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
